// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrYQ3-EjTf5oLbSKjMyzz6dk61LtK_jR0',
    appId: '1:215096397383:web:11f537f53f13f79590ab62',
    messagingSenderId: '215096397383',
    projectId: 'push-notifications-test-51f99',
    authDomain: 'push-notifications-test-51f99.firebaseapp.com',
    storageBucket: 'push-notifications-test-51f99.appspot.com',
    measurementId: 'G-R34ME1QX3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwxEhNli_0YJ_T9NzzY59HFU_I1djLl_E',
    appId: '1:215096397383:android:5dffe3bb33ca23af90ab62',
    messagingSenderId: '215096397383',
    projectId: 'push-notifications-test-51f99',
    storageBucket: 'push-notifications-test-51f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Nu-73SNSlB1QOXc_85312w57cUKB274',
    appId: '1:215096397383:ios:c4a1bb691567dd9690ab62',
    messagingSenderId: '215096397383',
    projectId: 'push-notifications-test-51f99',
    storageBucket: 'push-notifications-test-51f99.appspot.com',
    iosClientId: '215096397383-josoqtb4fhum50ttq0sv5q88os77sv88.apps.googleusercontent.com',
    iosBundleId: 'com.utkarsh.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Nu-73SNSlB1QOXc_85312w57cUKB274',
    appId: '1:215096397383:ios:c4a1bb691567dd9690ab62',
    messagingSenderId: '215096397383',
    projectId: 'push-notifications-test-51f99',
    storageBucket: 'push-notifications-test-51f99.appspot.com',
    iosClientId: '215096397383-josoqtb4fhum50ttq0sv5q88os77sv88.apps.googleusercontent.com',
    iosBundleId: 'com.utkarsh.pushNotifications',
  );
}
